# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('takeleave', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeleaveentry',
            name='department',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='takeleave.Department'),
            preserve_default=False,
        ),
    ]
